---
- name: consul-acl | Save managed token
  ansible.builtin.copy:
    content: "{{ consul_acl_master_token }}"
    dest: "{{ consul_dir_conf }}/.managed_token"
    mode: '0600'

- name: consul-acl | Create a policy with rules
  community.general.consul_policy:
    token: "{{ consul_acl_master_token }}"
    name: "{{ item.name }}"
    rules: "{{ item.rules }}"
  loop: "{{ consul_policy }}"
  when:
    - inventory_hostname == consul_master
    - consul_policy | length > 0

- name: consul-acl | Create a token
  community.general.consul_token:
    token: "{{ consul_acl_master_token }}"
    secret_id: "{{ item.token }}"
    policies:
      - name: "{{ item.name }}"
  loop: "{{ consul_policy }}"
  failed_when: false
  when:
    - inventory_hostname == consul_master
    - consul_policy | length > 0
